# Generated by Django 6.0.5 on 2026-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_task_archived_task_completed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
