# Generated by Django 6.0.5 on 2026-06-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_task_archived_alter_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
